import type { PlanContext } from './types.js';

/** Shared fixture: a three-station Circle covering the common capability mix. */
export function makeTestContext(): PlanContext {
  return {
    circle: {
      id: '11111111-1111-4111-8111-111111111111',
      name: 'Riverside Neighbors',
      circleType: 'neighborhood',
      circleTypeLabel: 'Neighborhood Radio Circle',
      areaLabel: 'Riverside district',
      gridOrLocalityLabel: null,
      shortDescription: 'Neighbors staying connected',
      purpose: 'Welfare checks during storms and outages.',
    },
    members: [
      {
        stationId: 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',
        stationName: 'Alpha Base',
        stationType: 'home',
        stationTypeLabel: 'Home',
        operatorName: 'Alice',
        circleRole: 'coordinator',
        circleRoleLabel: 'Circle coordinator',
        capabilities: ['frs', 'gmrs'],
        capabilityLabels: ['FRS (Family Radio Service)', 'GMRS (General Mobile Radio Service)'],
        areaLabel: 'Riverside district',
        gridIdentifier: '16SBK7308',
        experienceLevel: 'experienced',
        experienceLevelLabel: 'Experienced operator',
        authorization: 'gmrs_license',
        authorizationLabel: 'GMRS license',
        goals: ['neighborhood_welfare_checks'],
        participatesInScheduledChecks: true,
        willingToRelay: true,
        willingToActAsNetControl: true,
        receiveOnly: false,
        hypothetical: false,
        transmitPowerWatts: 50,
        antennaType: 'base_vertical',
        antennaTypeLabel: 'Base station vertical',
        antennaHeightFeet: 20,
        backupPower: ['battery'],
        backupPowerLabels: ['Battery bank'],
        repeaterLinks: [{ repeaterName: 'Ridge GMRS', access: 'rx_tx' }],
      },
      {
        stationId: 'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',
        stationName: 'Bravo Handheld',
        stationType: 'handheld',
        stationTypeLabel: 'Handheld radio',
        operatorName: 'Ben',
        circleRole: 'member',
        circleRoleLabel: 'Member',
        capabilities: ['frs'],
        capabilityLabels: ['FRS (Family Radio Service)'],
        areaLabel: null,
        gridIdentifier: null,
        experienceLevel: 'new',
        experienceLevelLabel: 'New to radio',
        authorization: 'frs_user',
        authorizationLabel: 'FRS user (no license required)',
        goals: ['receive_emergency_information'],
        participatesInScheduledChecks: true,
        willingToRelay: false,
        willingToActAsNetControl: false,
        receiveOnly: false,
        hypothetical: false,
        transmitPowerWatts: null,
        antennaType: null,
        antennaTypeLabel: null,
        antennaHeightFeet: null,
        backupPower: [],
        backupPowerLabels: [],
        repeaterLinks: [],
      },
      {
        stationId: 'cccccccc-cccc-4ccc-8ccc-cccccccccccc',
        stationName: 'Charlie Monitor',
        stationType: 'receive_only',
        stationTypeLabel: 'Receive-only monitoring position',
        operatorName: 'Cara',
        circleRole: 'member',
        circleRoleLabel: 'Member',
        capabilities: ['receive_only'],
        capabilityLabels: ['Receive-only'],
        areaLabel: 'Riverside district',
        gridIdentifier: null,
        experienceLevel: 'basic',
        experienceLevelLabel: 'Basic familiarity',
        authorization: null,
        authorizationLabel: null,
        goals: [],
        participatesInScheduledChecks: false,
        willingToRelay: false,
        willingToActAsNetControl: false,
        receiveOnly: true,
        hypothetical: false,
        transmitPowerWatts: null,
        antennaType: null,
        antennaTypeLabel: null,
        antennaHeightFeet: null,
        backupPower: [],
        backupPowerLabels: [],
        repeaterLinks: [],
      },
    ],
    scenario: {
      circumstances: ['power_outage', 'no_cellular', 'no_internet'],
      duration: 'hours_72',
      extent: 'citywide',
      notes: null,
    },
    scenarioDescription: 'Citywide event: power outage, no cellular coverage, no internet; lasting up to 72 hours.',
    repeaters: [
      {
        id: '22222222-2222-4222-8222-222222222222',
        name: 'Ridge GMRS',
        service: 'gmrs',
        serviceLabel: 'GMRS',
        outputFrequencyMhz: 462.6,
        offsetOrInput: '+5 MHz',
        tone: '141.3 Hz',
        areaLabel: 'Riverside district',
        status: 'active',
      },
    ],
    connectivity: null,
    generatedAt: '2026-08-01T12:00:00.000Z',
  };
}
