import type { PlanContext } from './types.js';

/** Shared fixture: a three-station Circle covering the common capability mix. */
export function makeTestContext(): PlanContext {
  return {
    circle: {
      id: '11111111-1111-4111-8111-111111111111',
      name: 'Riverside Neighbors',
      circleType: 'neighborhood',
      circleTypeLabel: 'Neighborhood Radio Circle',
      areaLabel: 'Riverside district',
      gridOrLocalityLabel: null,
      shortDescription: 'Neighbors staying connected',
      purpose: 'Welfare checks during storms and outages.',
    },
    members: [
      {
        stationId: 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',
        stationName: 'Alpha Base',
        stationType: 'home',
        stationTypeLabel: 'Home',
        operatorName: 'Alice',
        circleRole: 'coordinator',
        circleRoleLabel: 'Circle coordinator',
        capabilities: ['frs', 'gmrs'],
        capabilityLabels: ['FRS (Family Radio Service)', 'GMRS (General Mobile Radio Service)'],
        areaLabel: 'Riverside district',
        gridIdentifier: '16SBK7308',
        experienceLevel: 'experienced',
        experienceLevelLabel: 'Experienced operator',
        authorization: 'gmrs_license',
        authorizationLabel: 'GMRS license',
        goals: ['neighborhood_welfare_checks'],
        participatesInScheduledChecks: true,
        willingToRelay: true,
        willingToActAsNetControl: true,
        receiveOnly: false,
      },
      {
        stationId: 'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',
        stationName: 'Bravo Handheld',
        stationType: 'handheld',
        stationTypeLabel: 'Handheld radio',
        operatorName: 'Ben',
        circleRole: 'member',
        circleRoleLabel: 'Member',
        capabilities: ['frs'],
        capabilityLabels: ['FRS (Family Radio Service)'],
        areaLabel: null,
        gridIdentifier: null,
        experienceLevel: 'new',
        experienceLevelLabel: 'New to radio',
        authorization: 'frs_user',
        authorizationLabel: 'FRS user (no license required)',
        goals: ['receive_emergency_information'],
        participatesInScheduledChecks: true,
        willingToRelay: false,
        willingToActAsNetControl: false,
        receiveOnly: false,
      },
      {
        stationId: 'cccccccc-cccc-4ccc-8ccc-cccccccccccc',
        stationName: 'Charlie Monitor',
        stationType: 'receive_only',
        stationTypeLabel: 'Receive-only monitoring position',
        operatorName: 'Cara',
        circleRole: 'member',
        circleRoleLabel: 'Member',
        capabilities: ['receive_only'],
        capabilityLabels: ['Receive-only'],
        areaLabel: 'Riverside district',
        gridIdentifier: null,
        experienceLevel: 'basic',
        experienceLevelLabel: 'Basic familiarity',
        authorization: null,
        authorizationLabel: null,
        goals: [],
        participatesInScheduledChecks: false,
        willingToRelay: false,
        willingToActAsNetControl: false,
        receiveOnly: true,
      },
    ],
    generatedAt: '2026-08-01T12:00:00.000Z',
  };
}
